### ISSUE TITLE
ImportError: No module named 'cupshelpers'

### ISSUE THREAD

**Issue by juanitotc** [twaugh/system-config-printer#16]
I just compiled system-config-printer-1.5.7 from source:

1. Although I have /usr/local/bin/python3, the majority of the files were installed for /usr/bin/python3, one for /usr/bin/python and one correctly - maybe the shebang should be /usr/bin/env python3?

2. When I try to run system-config-printer, I get:

$ system-config-printer
Traceback (most recent call last):
  File "/usr/local/share/system-config-printer/system-config-printer.py", line 70, in <module>
    import cupshelpers
ImportError: No module named 'cupshelpers'

..but isn't system-config-printer itself meant to provide this?

3. Is there a run-time dep list somewhere for system-config-printer?

**Comment by twaugh** [comment]
Yes, ideally we'd code for python 3 with python 2 compatibility, with /usr/bin/python in the main script shebang.

Yes, system-config-printer provides `cupshelpers` itself. That's what the `install-exec-local` Makefile rule is meant to do. It sounds like it's been installed to the wrong place, or the path isn't picking it up.

No, there isn't a dependency list anywhere. :-( It definitely needs `pycups`, GTK+, and D-Bus.

**Comment by juanitotc** [comment]
OK, but that means I have to edit 60+ files to read "/usr/bin/env python3" as I have python3 in /usr/local/bin :(

This time things appear to have compiled properly and files have been installed in cupshelpers - maybe it was because I ran "make distclean" last time?

I make the following as recursive deps:

py3gobject, py3cups, dbus-python, gtk3-gir, polkit-gir, libnotify-gir, dconf and adwaita-icon-theme

Is cups-pk-helper required - it does not complain that it is missing?

It does complain the the typelib file for gnome-keyring is missing, but compiling gnome-keyring-3.16.0 does not produce any typelib files?

**Comment by twaugh** [comment]
cups-pk-helper is used if available but not required. It's for using polkit for cupsd auth.

I have a typelib file installed from libgnome-keyring. Sure it's not a build option?

**Comment by juanitotc** [comment]
I thought libgnome-keyring was depreciated (it stops at 3.12.0)?

**Comment by twaugh** [comment]
Could be.

**Comment by juanitotc** [comment]
BTW, it takes >20 seconds for system-config-printers to come up on a fast machine - what's it doing in this time?

**Comment by twaugh** [comment]
Not for me.

**Comment by juanitotc** [comment]
Hmm - thanks for your help anyway.

The test page does not want to print (what's new in the world of cups/hplip), but I need to do some more trouble-shooting on that...

**Comment by juanitotc** [comment]
In the gnome-3.16.x environment system-config-printer starts up immediately (I guess I was missing a dep outside the gnome environment) and at some stage printed a test page, so I believe this issue is solved.

Things don't want to work using the gnome-control-center printer applet - maybe due to gnome-keyring having replaced libgnome-keyring - but that would be the subject of a new issue if I can summon up the energy...

**Comment by jpopelka** [comment]
> so I believe this issue is solved

It's been 2 weeks, so I'm closing it.
