### ISSUE TITLE
Printer stopped/paused status  - "media-playback-pause" not showing

### ISSUE THREAD

**Issue by xes** [twaugh/system-config-printer#24]
Using Fedora 22 with system-config-printer 1.5.7-3, when a printer is disabled due an user action or a printer error i would expect to have a pause symbol near the printer image but nothing happens

Opening system-config-printer, all the printers seem to be always ready. 
Only opening the printer properties menu with the right mouse button i can check if printer is enabled or stopped.

Then, it would be great to have a more visible flag to identify stopped printers.
Very often desktop users CAN'T see that little pause symbol of media-playback-pause.png... 
...Maybe an old style red cross would be better? :)

**Comment by twaugh** [comment]
The compositing was wrong. Both offset and dest need to be the same when translating the smaller pixbuf.

**Comment by xes** [comment]
Sorry, to reopen this issue, but i have just discovered that also non critical notifications like the yellow triangle about "optical unit near end of line" (with the laser printer still working great) can hide the paused status of the printer.

At the point, the user stops using the printer thinking that the problem is the message related the triangle, while the real problem is that the printer is paused....
