### ISSUE TITLE
Ampersand in PPD *OpenGroup unhandled

### ISSUE THREAD

**Issue by pa-d-v** [twaugh/system-config-printer#25]
[EPSON-Epson-Stylus-SX235ppd.txt](https://github.com/twaugh/system-config-printer/files/67796/EPSON-Epson-Stylus-SX235ppd.txt)
system-config-printer doesn't seem to handle the ampersand & in *OpenGroup of above PPD well displaying &lt;b&gt;Paper & Quality options&lt;/b&gt; should be in bold (instead of showing the &lt;b&gt; signs) while cups webinterface does display it correctly.
![bug_printer](https://cloud.githubusercontent.com/assets/16370406/11917942/0ec0a9be-a71c-11e5-9f7b-6d36da3729a6.png)
Originally reported as [Ubuntu LP: #1523013](https://bugs.launchpad.net/ubuntu/+source/system-config-printer/+bug/1523013)

**Comment by jpopelka** [comment]
Fixed with 5f8a44ee637914ce8bf840b30b495056bc49ef02
