### ISSUE TITLE
D-Bus service file does not respect --prefix flag

### ISSUE THREAD

**Issue by bjornfor** [twaugh/system-config-printer#28]
Below is a build with ```--prefix=/nix/store/8p4w7v88winr0zlgqd08qnc4hh8picia-system-config-printer-1.3.12```. Still the dbus service file refers to /usr/bin, completely ignoring the supplied install prefix:

```
$ cat /nix/store/8p4w7v88winr0zlgqd08qnc4hh8picia-system-config-printer-1.3.12/share/dbus-1/services/org.fedoraproject.Config.Printing.service
[D-BUS Service]
Name=org.fedoraproject.Config.Printing
Exec=/usr/bin/scp-dbus-service
```

Tested version 1.3.12.

This bug breaks system-config-printer in NixOS, because it relies on these unique installation prefixes.

**Comment by twaugh** [comment]
Should be fixed now. Thanks for the report.

**Comment by bjornfor** [comment]
Thanks for the fix!
