### ISSUE TITLE
"CMD:<something>" append to the name of printers detected by dnss

### ISSUE THREAD

**Issue by bigon** [twaugh/system-config-printer#42]
Hi,

With version 1.5.7 it seems that all the printers detected y dnss get "CMD:<something>" append to their names

Not sure if related, but the driver detection is also failing for the printers detected by this method

**Comment by bigon** [comment]
Well this might actually be https://github.com/apple/cups/issues/4835

**Comment by twaugh** [comment]
Looks like that's the root cause, yes.

**Comment by bigon** [comment]
It's working in fedora because they carry a patch in cups for this
