### ISSUE TITLE
Incorrect default in dealing with a networked HP printer

### ISSUE THREAD

**Issue by mla1290** [twaugh/system-config-printer#9]
I have an HP OfficeJet 4620 fax/copier/printer/scanner connected to the network and need it to be configured as a printer on a machine which has a firewall and does not allow auto-discovery -- not a problem, since I know the printer's IP address. Running system-config-printer (the latest version, pulled down from github earlier today) I click on Add. In the resulting second window I click on Network Printer and then on Find Network Printer. The system is scanning in the meantime, but I am offered a window to enter a specific IP address, which I do and click on Find. I attach a screenshot of the result
![printerbug](https://cloud.githubusercontent.com/assets/1268757/8545079/f2ad2320-24a2-11e5-959f-9209b8ac855d.jpg)

The JetDirect option is selected as the default. This is problematic since, e.g. xsane is unable to find the printer for scanning. The problem goes away if I run hp-setup and tell it that I want a network printer and specify the address. This installs the printer with the URI of hp:/net..., which works for printing and scanning.

Curiously, if I wait for s-c-p to finish its searching for a network printer instead of typing supplying the IP address, it does find the printer, but things get only murkier as the result. Now no default is selected, but the first antry on offer is my printer with the correct IP address. Clicking on it, presents me with three options (see screenshot 
![printerbug1](https://cloud.githubusercontent.com/assets/1268757/8545268/b5261c9e-24a4-11e5-869e-73fad00d8dbb.jpg) The first is for Fax, which I do not need. The second is AppSocket/HP Jet Direct, which does not work with e.g. xsane. Only the third on is the correct HPLIP defined entry.

As a reasonably naive user I find this utterly confusing. Compared to that, printer configuration with HPLIP's hp-setup is simlpicity itself. Hence I echo the proposal made elsewhere: if s-c-p decides it is dealing with an HP printer, hand the whole operation to HPLIP.

**Comment by twaugh** [comment]
If the HPLIP 'hp' backend would discover network printers on its own -- or for that matter, if the hpaio SANE backend did -- this wouldn't be a problem. :-( Upstream bug: https://bugs.launchpad.net/hplip/+bug/1036461

However, the backend preference order shown in the screenshot, with Fax at the top, definitely looks like system-config-printer's fault. Having trouble reproducing it at the moment.

**Comment by mla1290** [comment]
It seems perfectly legitimate to have a firewall forbidding auto-discovery if auto-discovery is not required -- i.e. if one can supply explicit IP address. As I see it, there are two issues here. 

Firstly, the probe order defined in _do_find (line 242 of probe_printer.py) puts jetdirect probe first, with the hplip one near the end, just above smb probe. If hplip is moved to the top of the list, the default in the described scenario (my first screenshot) is correct (I've just checked that: 
![printerbug2](https://cloud.githubusercontent.com/assets/1268757/8546736/0c57099e-24b2-11e5-9d15-3ebc41d952fa.jpg)

Secondly, the option to enter a specific IP address is offered immediately, while the interfaces and then the network scan goes on. On a slowish machine it is very natural to assume that nothing much is happening and to enter the IP address, if known. Maybe display "Sanning, please wait" instead of a URI or IP address filed while automatic scan is in progress.

**Comment by mla1290** [comment]
NB: Fax is on the top because as can be seen on the same screenshot,  s-c-p for some reason reckons it is dealing specifically with the fax function of the printer -- that's what the device description it offers says.

**Comment by twaugh** [comment]
No, fax definitely shouldn't be at the top. I'm not sure why you're seeing that.
